<header>
    <nav class="page-size">
        <ul class="ul-xcwe">
            <li>
                <h3 class="logo">BlueWire</h3>
            </li>
        </ul>
        <ul class="ul-iewlc">
            <li>
                <a href="#">Firmwares</a>
            </li>
            <li>
                <a href="#">More</a>
            </li>
            <li>
                <a href="#">About</a>
            </li>
        </ul>
    </nav>
</header>