<script>
    let modals = <?php print_r($modals); ?>;
    let latest_devices = [];
    let data = [];
</script>
<header>
    <nav class="page-size">
        <ul class="ul-xcwe">
            <li>
                <a href="/">
                    <h3 class="logo">BlueWire</h3>
                </a>
            </li>
        </ul>
        <ul class="ul-iewlc">
            <li>
                <a href="#">Firmwares</a>
            </li>
            <li>
                <a href="#">More</a>
            </li>
            <li>
                <a href="#">About</a>
            </li>
        </ul>
    </nav>
</header>