<?php
require_once FRONTEND . 'header.phtml';
?>
<main>
    <?php require_once COMPONENTS . 'middle-view.php'; ?>
    <div class="home-bluf page-size">
        <div class="home-left">
            <div>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil architecto rem tempora maxime iure reprehenderit, ab unde voluptas a nesciunt ea porro? Saepe corporis officiis eius qui maiores omnis incidunt.
                Consectetur sed accusamus rerum voluptates est assumenda, accusantium totam illo consequuntur provident fuga adipisci id aut neque ut ipsum doloribus nisi sapiente, sequi beatae dolores molestias. Velit vitae est culpa.
                Quae animi ullam, vero aliquam nemo repudiandae culpa neque quam quisquam consectetur porro exercitationem consequuntur officiis eveniet debitis illum pariatur recusandae? Repudiandae sint dolorum quae doloribus, deserunt neque explicabo impedit.
                Neque, eius rem aliquid quia voluptatem consectetur itaque harum vel est labore quas nisi error officiis fugit eum, nihil minus numquam laudantium ratione earum quo placeat ab. Vitae, error nostrum!
            </div>
            <div></div>
            <div class="reflex-item">
                <div class="items">
                    <div class="item-title-bar">
                        <span class="title">Mobile Firmware Library name</span>
                        <?php require_once COMPONENTS . 'share-buttons.php' ?>
                    </div>
                </div>
            </div>
            <div>
                <div class="search-input">
                    <i class="fa fa-mobile"></i>
                    <div id="search-wrap" class="home">
                        <input type="text" id="search-input" placeholder="Search a model..." class="search-input">
                        <div class="srch-results">
                        </div>
                    </div>
                </div>
                <div class="items-list">
                    <?php
                    while ($items = $query->fetch_all(MYSQLI_ASSOC)) {

                        foreach ($items as $item) {
                            $name = $item['name'];
                            $image = $item['image'];
                            $id = $item['id'];
                            $deviceCode = $item['deviceCode'];
                            $cntry = $item['countries'];
                    ?>

                            <a href="/?page=view&id=<?php echo $id; ?>">
                                <div class="item-cell">
                                    <img src="<?php echo $image == '' ? "https://mifirm.net/assets/img/model/xiaomi-redmi-note-11-pro-global.jpg" : $image; ?>" alt="...">
                                    <br>
                                    <h5><?php echo $name; ?></h5>

                                    <?php echo $deviceCode != '' ? '<span class="modal-code">(' . $deviceCode . ')</span>' : '' ?>
                                    <div class="type">
                                        <?php
                                        $countries = explode(',', $cntry);
                                        foreach ($countries as $c) {
                                            if ($c != '') {
                                                $t = rand(0, $colorsLen);
                                        ?>
                                                <span style="background: <?php echo $colors[$t]; ?>" class="title"><?php echo $c; ?></span>
                                        <?php }
                                        } ?>
                                    </div>
                                </div>
                            </a>
                    <?php
                        }
                    }

                    ?>

                </div>
            </div>
        </div>
        <?php require_once COMPONENTS . 'side-bar.php' ?>
    </div>
</main>