<?php
require_once FRONTEND . 'header.phtml';
?>
<main>
    <?php require_once COMPONENTS . 'middle-view.php'; ?>
    <div class="home-bluf page-size">
        <div class="home-left">
            <div>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil architecto rem tempora maxime iure reprehenderit, ab unde voluptas a nesciunt ea porro? Saepe corporis officiis eius qui maiores omnis incidunt.
                Consectetur sed accusamus rerum voluptates est assumenda, accusantium totam illo consequuntur provident fuga adipisci id aut neque ut ipsum doloribus nisi sapiente, sequi beatae dolores molestias. Velit vitae est culpa.
                Quae animi ullam, vero aliquam nemo repudiandae culpa neque quam quisquam consectetur porro exercitationem consequuntur officiis eveniet debitis illum pariatur recusandae? Repudiandae sint dolorum quae doloribus, deserunt neque explicabo impedit.
                Neque, eius rem aliquid quia voluptatem consectetur itaque harum vel est labore quas nisi error officiis fugit eum, nihil minus numquam laudantium ratione earum quo placeat ab. Vitae, error nostrum!
            </div>
            <div></div>
            <div class="reflex-item">
                <div class="items">
                    <div class="item-title-bar">
                        <span class="title">Mobile Firmware Library name</span>
                        <?php require_once COMPONENTS . 'share-buttons.php' ?>
                    </div>
                </div>
            </div>
            <div>
                <div class="card-body">
                    <div class="table-responsive-xl">
                    <table class="kakxmsdkl table table-hover w-100 d-block d-md-table small">
                        <thead>
                            <tr>
                                <th scope="col">Samsung Device</th>
                                <th scope="col">CSC</th>
                                <th scope="col">Version</th>
                                <th scope="col">Bit/SW REV. 
                                    Security Patch Lvl.</th>
                                <th scope="col">OS</th>
                                <th scope="col">Build date</th>
                                <th scope="col">Updated</th>
                                <th scope="col">Status</th>
                            </tr>
                        </thead>
                        
                        <tfoot>
                            <tr>
                                <th>Samsung Device</th>
                                <th>CSC</th>
                                <th>Version</th>
                                <th>Bit/SW REV. 
                                    Security Patch Lvl.</th>
                                <th>OS</th>
                                <th>Build date</th>
                                <th>Updated</th>
                                <th>Status</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            <tr  class="text-dark bg-light">
                                <td style="min-width: 180px">
                                    <a href="https://samfw.com/firmware/SM-G780F" title="SM-G780F / Galaxy S20 Fan Edition">
                                        SM-G780F
                                    </a>
                                    <span class="badge badge-light badge-pill pull-right float-right ml-1" style="cursor: pointer;" title="Notification when new update" data-toggle="modal" data-target="#noticeUpdate" id="noticeUpdatebutton" data-modelname="" data-modelcode="SM-G780F" data-modelregion="XXV"><i class="fas fa-bell"></i></span>
                                </td>
                                <td>
                                    <a href="https://samfw.com/firmware/SM-G780F/XXV">
                                        <span class="flag flag-vn flag-small "></span> XXV
                                    </a>
                                </td>
                                <td>
                                    <a href="javascript:void(0);" title="Download Samsung Firmware/ROM for SM-G780F (XXV) version G780FXXUADVI1">G780FXXUADVI1</a>
                                </td>
                                <td class="text-success font-weight-bold">
                                    1
                                    <span class="badge badge-pill badge-dark">Full Files</span> 
                                </td>
                                <td>
                                    S(Android 12)
                                </td>
                                <td>
                                    20220919210711
                                </td>
                                <td>
                                    2022-09-26 22:45:54
                                </td>
                                <td>
                                    <span class="text-success"><i class="faa-float animated far fa-arrow-alt-circle-up"></i> Uploading</span>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                    </div>
                </div>
            </div>
            <div class="reflex-item">
                <div class="items">
                    <div class="item-title-bar">
                        <i class="fas fa-file-archive"></i>
                        <span class="title"> New combinations</span>
                    </div>
                </div>
            </div>
            <div>
                <div class="card-body">
                    <div class="table-responsive-xl">
                    <table class="kakxmsdkl table table-hover w-100 d-block d-md-table small">
                        <thead>
                            <tr>
                                <th>Device</th>
                                <th>Version</th>
                                <th>Bit/SW REV.</th>
                                <th>FA</th>
                                <th>Change list</th>
                                <th>Update</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        
                        <tfoot>
                            <tr>
                                <th>Device</th>
                                <th>Version</th>
                                <th>Bit/SW REV.</th>
                                <th>FA</th>
                                <th>Change list</th>
                                <th>Update</th>
                                <th>Status</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            <tr  class="text-dark bg-light">
                                <td style="min-width: 180px">
                                    <a href="/comination/SM-G780F" title="SM-G780F / Galaxy S20 Fan Edition">
                                        SM-G9287C / Galaxy S6 edge
                                    </a>
                                    <span class="badge badge-light badge-pill pull-right float-right ml-1" style="cursor: pointer;" title="Notification when new update" data-toggle="modal" data-target="#noticeUpdate" id="noticeUpdatebutton" data-modelname="" data-modelcode="SM-G780F" data-modelregion="XXV"><i class="fas fa-bell"></i></span>
                                </td>
                                <td>
                                    <a href="/comination/SM-G780F/XXV">
                                        G9287CDXU2AOJ1
                                    </a>
                                </td>
                                <td>
                                    <a href="javascript:void(0);" title="Download Samsung Firmware/ROM for SM-G780F (XXV) version G780FXXUADVI1">G780FXXUADVI1</a>
                                </td>
                                <td class="text-success font-weight-bold">
                                    1
                                </td>
                                <td>
                                    FA
                                </td>
                                <td>
                                    CL5994902
                                </td>
                                <td>
                                    2022-09-26 22:45:54
                                </td>
                                <td>
                                    <span class="text-success"><i class="faa-pulse animated far fa-check-circle"></i>  Ready</span>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                    </div>
                </div>
            </div>
        </div>
        <?php require_once COMPONENTS . 'side-bar.php' ?>
    </div>
</main>