<?php
require_once FRONTEND . 'header.phtml';
?>
<main>
    <?php require_once COMPONENTS . 'middle-view.php'; ?>

    <div class="home-bluf page-size">
        <div class="home-left">
            <div class="head-links">
                <a href="<?php echo URLFormate('/') ?>">Home</a> /
                <a class="active" href="<?php echo URLFormate('view', '32') ?>">Device Name</a>
            </div>
            <div class="closable-wrap  flex-around">
                <a href="#">
                    <i class="fa fa-rss"></i>
                    BlueWire FRP Tool 2.7.1 - Remove Samsung FRP one click
                    <i class="fa fa-external-link"></i>

                </a>
                <button onclick="handleClose(this)">&times;</button>
            </div>
            <div class="reflex-head-hu">
                <div class="items">
                    <div class="item-title-bar">
                        <span class="title">Download Xiaomi Redmi 5 Firmware - Redmi 5 ROM TWRP Files</span>
                        <div class="item-ckw">
                            <div class="shareable-links">
                                <div>
                                    <span onclick="handleShare()">
                                        <i class="fa fa-share-alt"></i> share
                                    </span>
                                    <a href="#">
                                        <i class="fa fa-at"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fa fa-linkedin"></i>
                                    </a>
                                    <a href="#">

                                        <i class="fa fa-twitter"></i>
                                    </a>
                                    <a href="#">

                                        <i class="fa fa-whatsapp"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fa fa-telegram"></i>

                                    </a>
                                    <a href="#">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="device-showcase">
                <img src="https://mifirm.net/assets/img/model/xiaomi-redmi-note-11-pro-global.jpg" alt="">
                <div class="right">
                    <p>
                        Xiaomi Redmi 5 with codename is rosy Firmware includes Global Firmware (Global ROM), China Firmware (China ROM), Stable MIUI and Beta MIUI. This is full list of Xiaomi Redmi 5. Xiaomi Redmi 5 may called with other names like MDG1, MDI1, MDE1, MDT1. China ROM, Firmware is for China region, there are only English, Chinese and No Google Services. Global ROM, Firmware is for Global region and almost can flash for China phone with unlocked bootloader. They have multilanguage and Google Services, china apps removed. All file download from MiFirm is Free. Fastboot firmware, ZIP firmware is official from Xiaomi. EU ROM, TWRP and Other files is unofficial. Use at your own risk.
                    </p>
                    <div class="short-details">
                        <div class="item">
                            <i class="fa fa-calendar"></i>
                            <span>
                                Released 2020, October 02
                            </span>
                        </div>
                        <div class="item">
                            <i class="fa fa-mobile"></i>
                            <span>
                                190g, 8.4mm thickness
                            </span>
                        </div>
                        <div class="item">
                            <i class="fa fa-android"></i>
                            <span>
                                Android 7.1.2, MIUI 11
                            </span>
                        </div>
                        <div class="item">
                            <i class="fa fa-hdd-o"></i>
                            <span>
                                16GB/32GB/64GB storage, microSDXC
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="more-details">
                <section>
                    <span class="title">Networks</span>
                    <table>
                        <tr>
                            <th>Technology</th>
                            <td>GSM / CDMA / HSPA / EVDO / LTE / 5G</td>
                        </tr>
                        <tr>
                            <th>3G</th>
                            <td>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora nobis vel repellat veniam fugit? Aspernatur, nulla sunt. Porro, perferendis delectus tempore temporibus voluptate similique eius veniam quibusdam nulla quae ipsam.</td>
                        </tr>
                        </thead>
                    </table>
                </section>
                <section>
                    <span class="title">TIMELINE</span>
                    <table>
                        <tr>
                            <th>Announced</th>
                            <td>2020, September 23</td>
                        </tr>
                        <tr>
                            <th>Released</th>
                            <td>Released 2020, October 02</td>
                        </tr>
                        </thead>
                    </table>
                </section>
                <section>
                    <span class="title">BODY</span>
                    <table>
                        <tr>
                            <th>Dimensions</th>
                            <td>159.8 x 74.5 x 8.4 mm (6.29 x 2.93 x 0.33 in)</td>
                        </tr>
                        <tr>
                            <th>Weight</th>
                            <td>190 g (6.70 oz)</td>
                        </tr>
                        <tr>
                            <th>Build</th>
                            <td>Glass front, plastic back, aluminum frame</td>
                        </tr>
                        <tr>
                            <th>SIM</th>
                            <td>190 g (6.70 oz)Single SIM (Nano-SIM) or Hybrid Dual SIM (Nano-SIM, dual stand-by)</td>
                        </tr>
                        </thead>
                    </table>
                </section>
                <section>
                    <span class="title">DISPLAY</span>
                    <table>
                        <tr>
                            <th>Card slot</th>
                            <td>microSDXC (uses shared SIM slot)</td>
                        </tr>
                        <tr>
                            <th>Internal</th>
                            <td>128GB 6GB RAM, 128GB 8GB RAM, 256GB 8GB RAM
                                UFS 3.1</td>
                        </tr>
                        </thead>
                    </table>
                </section>
            </div>
            <div class="closable-wrap  flex-around">
                <span>
                    <i class="fa fa-list"></i>
                    Samsung firmware SM-G781U / Galaxy S20 Fan Edition 5G SM-G781U <span class="tag-2">521</span>
                </span>
            </div>
            <div class="more-like-dv">
                <table>
                    <thead>
                        <tr>
                            <th>Device</th>
                            <th>CSC</th>
                            <th>Version</th>
                            <th>Bit/SW Rev.? Security Patch Lvl.</th>
                            <th>OS</th>
                            <th>Build date</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Samsung Galaxy S20 Fan Edition 5G</td>
                            <td>DSH</td>
                            <td>G781USQS7FVD4</td>
                            <td>7 2022-05-01 full Files</td>
                            <td>S(Android 12)</td>
                            <td>20220505162120</td>
                        </tr>
                        <tr>
                            <td>Samsung Galaxy S20 Fan Edition 5G</td>
                            <td>DSH</td>
                            <td>G781USQS7FVD4</td>
                            <td>7 2022-05-01 full Files</td>
                            <td>S(Android 12)</td>
                            <td>20220505162120</td>
                        </tr>
                        <tr>
                            <td>Samsung Galaxy S20 Fan Edition 5G</td>
                            <td>DSH</td>
                            <td>G781USQS7FVD4</td>
                            <td>7 <span class="tag-1">2022-05-01</span> <span class="tag-2">full Files</span></td>
                            <td>S(Android 12)</td>
                            <td>20220505162120</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="home-right">
            <div>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati necessitatibus, quo dolorum ut harum ad, debitis suscipit tempora molestiae veritatis magni nobis iusto! Tenetur laudantium minus consequatur nostrum, voluptatem corrupti!
            </div>
            <div>

                Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati necessitatibus, quo dolorum ut harum ad, debitis suscipit tempora molestiae veritatis magni nobis iusto! Tenetur laudantium minus consequatur nostrum, voluptatem corrupti!
            </div>
        </div>
    </div>
</main>