<?php
require_once FRONTEND . 'header.phtml';
?>
<main>
    <?php require_once COMPONENTS . 'middle-view.php'; ?>

    <div class="home-bluf page-size">
        <div class="home-left">
            <div class="head-links">
                <a href="<?php echo URLFormate('/') ?>">Home</a> /
                <a class="active" href="<?php echo URLFormate('view', '32') ?>">Device Name</a>
            </div>
            <div class="closable-wrap  flex-around">
                <a href="#">
                    <i class="fa fa-rss"></i>
                    BlueWire FRP Tool 2.7.1 - Remove Samsung FRP one click
                    <i class="fa fa-external-link"></i>

                </a>
                <button onclick="handleClose(this)">&times;</button>
            </div>
            <div></div>
            <div class="reflex-head">
                <div class="items">
                    <div class="item-title-bar">
                        <span class="title">Mobile Firmware Library name</span>
                        <div class="item-ckw">

                            <div class="shareable-links">
                                <div>
                                    <span onclick="handleShare()">
                                        <i class="fa fa-share-alt"></i> share
                                    </span>
                                    <a href="#">
                                        <i class="fa fa-at"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fa fa-linkedin"></i>
                                    </a>
                                    <a href="#">

                                        <i class="fa fa-twitter"></i>
                                    </a>
                                    <a href="#">

                                        <i class="fa fa-whatsapp"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fa fa-telegram"></i>

                                    </a>
                                    <a href="#">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="filters">
                                <select name="" id="">
                                    <option value="">Date</option>
                                    <option value="">Name</option>
                                </select>
                                <select style="" name="" id="">
                                    <option value="">All</option>
                                    <option value="">China</option>
                                    <option value="">Global</option>
                                    <option value="">EEA</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="search-input">
                    <i class="fa fa-mobile"></i>
                    <input type="text" placeholder="Search a model..." class="search-input">
                </div>
                <div class="items-list">
                    <a href="#">
                        <div class="item-cell">
                            <img src="https://mifirm.net/assets/img/model/xiaomi-redmi-note-11-pro-global.jpg" alt="...">
                            <br>
                            <h5>Redmi Note 11 Pro 4G</h5>
                            <span class="modal-code">(Vida)</span>
                            <div class="type">
                                <span style="background: #ffaec9" class="title">IN</span>
                                <span style="background: #c0f97d" class="title">PAK</span>
                                <span class="title">AFG</span>
                            </div>
                        </div>
                    </a>
                    <a href="#">
                        <div class="item-cell">
                            <img src="https://mifirm.net/assets/img/model/xiaomi-redmi-note-11-pro-global.jpg" alt="...">
                            <br>
                            <h5>Redmi Note 11 Pro 4G</h5>
                            <span class="modal-code">(Vida)</span>
                            <div class="type">
                                <span class="title">IN</span>
                            </div>
                        </div>
                    </a>
                    <a href="#">
                        <div class="item-cell">
                            <img src="https://mifirm.net/assets/img/model/xiaomi-redmi-note-11-pro-global.jpg" alt="...">
                            <br>
                            <h5>Redmi Note 11 Pro 4G</h5>
                            <span class="modal-code">(Vida)</span>
                            <div class="type">
                                <span class="title">IN</span>
                            </div>
                        </div>
                    </a>
                    <a href="#">
                        <div class="item-cell">
                            <img src="https://mifirm.net/assets/img/model/xiaomi-redmi-note-11-pro-global.jpg" alt="...">
                            <br>
                            <h5>Redmi Note 11 Pro 4G</h5>
                            <span class="modal-code">(Vida)</span>
                            <div class="type">
                                <span class="title">IN</span>
                            </div>
                        </div>
                    </a>
                    <a href="#">
                        <div class="item-cell">
                            <img src="https://mifirm.net/assets/img/model/xiaomi-redmi-note-11-pro-global.jpg" alt="...">
                            <br>
                            <h5>Redmi Note 11 Pro 4G</h5>
                            <span class="modal-code">(Vida)</span>
                            <div class="type">
                                <span class="title">IN</span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="home-right">
            <div>

                Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati necessitatibus, quo dolorum ut harum ad, debitis suscipit tempora molestiae veritatis magni nobis iusto! Tenetur laudantium minus consequatur nostrum, voluptatem corrupti!
            </div>
            <div>

                Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati necessitatibus, quo dolorum ut harum ad, debitis suscipit tempora molestiae veritatis magni nobis iusto! Tenetur laudantium minus consequatur nostrum, voluptatem corrupti!
            </div>
        </div>

    </div>
</main>