<?php
$sql = "SELECT * FROM devices WHERE 1 ORDER BY id DESC LIMIT 25";
$query = $con->query($sql);
$data = [];
if ($query->num_rows > 0) {
    $data = $query->fetch_all(MYSQLI_ASSOC);
}

?>

<div class="list-view">
    <h3>Devices List</h3>
    <?php
    if (count($data) > 0) {
    ?>
        <table id="example" class="table table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Device</th>
                    <th>Description</th>
                    <th>Action</th>
                    <th>Added At</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($data as $item) {
                ?>
                    <tr style="background: <?php echo $item['status'] == 1 ? '#25ff001c' : '#e91e630d' ?>">
                        <td><?php echo $item['id']; ?></td>
                        <td><?php echo $item['name']; ?></td>
                        <td><?php

                            echo strlen($item['description']) > 100 ?  substr($item['description'], 0, 100) . '...' : $item['description'];
                            ?></td>
                        <td>
                            <button class="status" onclick="handleStatus(<?php echo $item['id'] ?>,status=<?php echo $item['status']; ?>,confirm=false, device='<?php echo $item['name']; ?>')"><?php echo $item['status'] == 1 ? 'Disable' : 'Active' ?></button>
                            <button class="edit" onclick="handleEdit(<?php echo $item['id'] ?>, confirm=false, device='<?php echo $item['name']; ?>' )">Edit</button>
                            <button onclick="handleDelete(<?php echo $item['id'] ?>,confirm=false, device='<?php echo $item['name']; ?>')">Delete</button>
                            <button class="status" onclick="window.location.href = `/admin.php?page=add-firmware&file=<?php echo $item['id'] ?>&name=<?php echo $item['name']; ?>`"><i class="fa fa-plus"></i></button>
                        </td>
                        <td><?php echo date_format(date_create($item['createdAt']), 'd M Y') ?></td>
                    </tr>
                <?php
                }
                ?>
            </tbody>
            <tfoot>
                <tr>
                    <th>ID</th>
                    <th>Device</th>
                    <th>Description</th>
                    <th>Action</th>
                    <th>Added At</th>
                </tr>
            </tfoot>
        </table>
    <?php
    } else {
    ?>
        <h2 style="display:block;text-align:center;margin:50px auto;">
            There is no data found!
        </h2>
    <?php
    }
    ?>
</div>