<header>
    <nav class="page-size">
        <ul class="ul-xcwe">
            <li>
                <h3 class="logo">BlueWire</h3>
            </li>
        </ul>
        <ul class="ul-iewlc">
            <li>
                <a style="color: white; font-weight:bold;text-transform:uppercase;" href="/admin.php?view=logout"> <span><?php echo $isLogged != 0 ? $isLogged : 'Not logged' ?></span></a>
            </li>
        </ul>
    </nav>
</header>