<?php
require_once BACKEND . 'head.php';
require_once FRONTEND . 'header.phtml';

if (!$isLogged) {
    echo '<script>window.location.href = "/admin.php?view=login"</script>';
    header('location: /admin.php?view=login');
}
?>
<main>
    <div id="heavy-modal"></div>
    <div class="admin-main page-size">

        <div class="message-box">
            <?php if (isset($_SESSION['message']) && $_SESSION['message'] != '') {
            ?>
                <div class="message open <?php echo $_SESSION['message']['type']; ?>">
                    <span class="text close" onclick="handleMessage(this)">&times;</span>
                    <span class="text"><?php echo $_SESSION['message']['text']; ?></span>
                </div>
            <?php
                unset($_SESSION['message']);
            }
            ?>
        </div>

        <div class="view-alert">
        </div>

        <div class="xyz-left">
            <div class="flex">
                <h3 style="letter-spacing:1px">BlueFire Admin</h3>
                <span>
                    <i class="fa fa-feather"></i>
                </span>

            </div>
            <div class="left-ul">
                <a class="dashboard" href='/admin.php?page=dashboard'>
                    <div></div>
                    <div></div>
                    <span>
                        <i class="fa fa-dashboard"></i>Dashboard
                    </span>
                    <i class="fa fa-caret-right"></i>
                </a>
                <a id="edit-li" class="device-list" href='/admin.php?page=device-list'>
                    <div></div>
                    <div></div>
                    <span>
                        <i class="fa fa-mobile"></i>Devices List
                    </span>
                    <i class="fa fa-caret-right"></i>
                </a>
                <a href='/admin.php?page=add-device' class="add-device">
                    <div></div>
                    <div></div>
                    <span>
                        <i class="fa fa-plus"></i>Add Devices
                    </span>
                    <i class="fa fa-caret-right"></i>
                </a>
                <a href='/admin.php?page=firmware-list' class="firmware-list">
                    <div></div>
                    <div></div>
                    <span>
                        <i class="fa fa-cogs"></i>Firmware List
                    </span>
                    <i class="fa fa-caret-right"></i>
                </a>
                <a href='/admin.php?page=add-firmware' class="add-firmware">
                    <div></div>
                    <div></div>
                    <span>
                        <i class="fa fa-cog"></i>Add Firmware
                    </span>
                    <i class="fa fa-caret-right"></i>
                </a>
                <a href='/admin.php?page=edit-device' class="edit-device">
                    <div></div>
                    <div></div>
                    <span>
                        <i class="fa fa-edit"></i>Edit Devices
                    </span>
                    <i class="fa fa-caret-right"></i>
                </a>
                <a href='/admin.php?page=modals' class="modals">
                    <div></div>
                    <div></div>
                    <span>
                        <i class="fa fa-feather"></i>Modals
                    </span>
                    <i class="fa fa-caret-right"></i>
                </a>
            </div>
        </div>
        <div class="xyz-right">
            <div class="admin-top-view">
                <span><i class="fa fa-bars"></i></span>
                <input type="search" placeholder="Enter to search">
                <span>LittleZabi</span>
            </div>
            <div id="render-view">