<?php
// require_once FRONTEND . 'header.phtml';

if (!$isLogged) {
    echo '<script>window.location.href = "/admin.php?view=login"</script>';
    header('location: /admin.php?view=login');
}
?>
<main>
    <div id="heavy-modal"></div>
    <div class="admin-main page-size">

        <div class="message-box">
            <?php if (isset($_SESSION['message']) && $_SESSION['message'] != '') {
            ?>
                <div class="message open <?php echo $_SESSION['message']['type']; ?>">
                    <span class="text close" onclick="handleMessage(this)">&times;</span>
                    <span class="text"><?php echo $_SESSION['message']['text']; ?></span>
                </div>
            <?php
                unset($_SESSION['message']);
            }
            ?>
        </div>

        <div class="view-alert">
        </div>

        <div class="xyz-left">
            <div class="flex">
                <h3 style="letter-spacing:1px">BlueFire Admin</h3>
                <span>
                    <i class="fa fa-feather"></i>
                </span>

            </div>
            <ul class="left-ul">
                <li onclick="handlePage('dashboard',this)">
                    <div></div>
                    <div></div>
                    <span>
                        <i class="fa fa-dashboard"></i>Dashboard
                    </span>
                    <i class="fa fa-caret-right"></i>
                </li>
                <li onclick="handlePage('list', this)">
                    <div></div>
                    <div></div>
                    <span>
                        <i class="fa fa-mobile"></i>Devices List
                    </span>
                    <i class="fa fa-caret-right"></i>
                </li>
                <li onclick="handlePage('add-new',this)">
                    <div></div>
                    <div></div>
                    <span>
                        <i class="fa fa-plus"></i>Add Devices
                    </span>
                    <i class="fa fa-caret-right"></i>
                </li>
                <li id="edit-li" onclick="handlePage('edit',this)">
                    <div></div>
                    <div></div>
                    <span>
                        <i class="fa fa-edit"></i>Edit Devices
                    </span>
                    <i class="fa fa-caret-right"></i>
                </li>
                <li onclick="handlePage('modals-list',this)">
                    <div></div>
                    <div></div>
                    <span>
                        <i class="fa fa-feather"></i>Modals
                    </span>
                    <i class="fa fa-caret-right"></i>
                </li>
            </ul>
        </div>
        <div class="xyz-right">
            <div class="admin-top-view">
                <span><i class="fa fa-bars"></i></span>
                <input type="search" placeholder="Enter to search">
                <span>LittleZabi</span>
            </div>
            <div id="render-view"></div>
        </div>
    </div>
</main>