<div class="list-view">
    <div class="title-and-btn">
        <h3>Modals List</h3>
        <button onclick="newModal()" title="add new modal">Add new Modal</button>
    </div>

    <?php
    if (count($data) > 0) {
    ?>

        <table id="example">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Body</th>
                    <th>Status</th>
                    <th>Action</th>
                    <th>Added At</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($data as $item) {
                ?>
                    <tr style="background: <?php echo $item['status'] == 1 ? '#25ff001c' : '#e91e630d' ?>">
                        <td><?php echo $item['id']; ?></td>
                        <td><?php echo $item['title']; ?></td>
                        <td><?php echo $item['body'] ?></td>
                        <td><?php echo $item['status'] ? 'Active' : 'Disabled' ?></td>
                        <td>
                            <button class="status" onclick="handleModalStatus(<?php echo $item['id'] ?>,status=<?php echo $item['status']; ?>,confirm=false, device='<?php echo $item['title']; ?>')"><?php echo $item['status'] == 1 ? 'Disable' : 'Active' ?></button>
                            <button class="edit" onclick="handleModalsEdit(<?php echo $item['id'] ?>, title='<?php echo $item['title']; ?>', text=`<?php echo $item['body']; ?>`)">Edit</button>
                            <button onclick="handleDeleteModal(<?php echo $item['id'] ?>, title='<?php echo $item['title']; ?>')">Delete</button>
                        </td>
                        <td><?php echo date_format(date_create($item['createdAt']), 'd M Y') ?></td>
                    </tr>
                <?php
                }
                ?>

            </tbody>
        </table>
    <?php
    } else {
    ?>
        <h2 style="display:block;text-align:center;margin:50px auto;">
            There is no data found!
        </h2>
    <?php
    }
    ?>
</div>